# Generated by Django 2.2.6 on 2019-10-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiddenJobs',
            new_name='HiddenJob',
        ),
        migrations.RenameModel(
            old_name='SeenJobs',
            new_name='SeenJob',
        ),
        migrations.CreateModel(
            name='SearchPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
