"""job table

Revision ID: f59525ae36a0
Revises: 
Create Date: 2018-11-29 12:36:52.420371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59525ae36a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=30), nullable=True),
    sa.Column('date_posted', sa.String(length=10), nullable=True),
    sa.Column('not_interested', sa.Boolean(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_date_posted'), 'job', ['date_posted'], unique=False)
    op.create_index(op.f('ix_job_employer'), 'job', ['employer'], unique=False)
    op.create_index(op.f('ix_job_not_interested'), 'job', ['not_interested'], unique=False)
    op.create_index(op.f('ix_job_seen'), 'job', ['seen'], unique=False)
    op.create_index(op.f('ix_job_url'), 'job', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_url'), table_name='job')
    op.drop_index(op.f('ix_job_seen'), table_name='job')
    op.drop_index(op.f('ix_job_not_interested'), table_name='job')
    op.drop_index(op.f('ix_job_employer'), table_name='job')
    op.drop_index(op.f('ix_job_date_posted'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
